# The URL the site will be built for
base_url = "https://elrod.me"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

build_search_index = true
default_language = "en"

theme = "tabi"
title = "rick elrod"

generate_feeds = true
taxonomies = [{name = "tags", feed = true}]


[markdown]
highlight_code = true
highlight_theme = "css"

[extra]
skin = "blue"
mermaid = true
serve_local_mermaid = false
socials = [
    { name = "github", url = "https://github.com/relrod", icon = "github" },
    { name = "linkedin", url = "https://linkedin.com/in/elrodrick", icon = "linkedin" },
    { name = "bluesky", url = "https://bsky.app/profile/relrod.bsky.social", icon = "bluesky" },
    { name = "mastodon", url = "https://fosstodon.org/@relrod", icon = "mastodon" },
]
fediverse_creator = { handle = "relrod", domain = "fosstodon.org" }

[search]
index_format = "elasticlunr_json"
include_title = true
include_description = true
include_path = true
include_content = true
